# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190318_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
