# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190318_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playing',
            field=models.CharField(default='', max_length=3),
        ),
    ]
